### ISSUE TITLE
This Github/WinIMerge repo is not up-to-date with the BitBucket repo.

### ISSUE THREAD

**Issue by GreyMerlin** [sdottaka/winimerge#4]
The latest commit in this GitHub repo is 25 March 2017, merging my "_Merge tag 1.0.6.0_" commit of 23 March.

The latest commit in the BitBucket repo is 30 Aug 2017, your "_Merge tag 1.0.7.0_" commit after merging my "_VS2017 - Update BuildBin and .sln files_" commit of 26 July.

I now have some old commits from July (dealing with **VS2017**) and new commits from December (dealing with **C++17**).  I noticed these missing commits back in July, but then forgot to report them to you.

I will generate a new Pull Request to incorporate all these commits when your GitHub repo gets brought up-to-date

Happy Holidays :)
Bill

**Comment by sdottaka** [comment]
Thank you for letting me know.
I've updated this repository.
